FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt requirements-ml.txt ./
RUN pip install --no-cache-dir -r requirements.txt -r requirements-ml.txt
COPY app ./app
COPY training_service.py .
CMD ["uvicorn", "training_service:app", "--host", "0.0.0.0", "--port", "15000"]
